# Site settings
baseURL = "https://edexcellencepiedmont.com"
languageCode = "en-us"
title = "PEEP"
theme = "fortyone"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Parents for Educational Excellence in Piedmont"
  description = "PEEP"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Parents for Educational Excellence in Piedmont"
    subtitle = "(PEEP)"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Best Practices"
      url = "https://docs.google.com/forms/d/12DxD1Cb9urpHC6LFK4ArmorvEPlu0CoePFoNIxZ5QUY/edit"

    [[params.navigation.links]]
      name = "CAASPP / CAST test results"
      url = "/attachments/"

    [[params.navigation.links]]
      name = "College Matriculation"
      url = "https://harititan.com/article/matriculation-counts"

    [[params.navigation.links]]
      name = "Donate to support PEEP"
      url = "https://www.paypal.com/donate/?hosted_button_id=ZWQ6MRRWALRXQ"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Become a member"
      url = "https://docs.google.com/forms/d/1ZyCV3GPZcpFEl358rIU9WYL8WZyWwZKdcTdVvxLuVjc/edit"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.webp' in
    # the 'static/img' folder.
    title = "PEEP School Board Candidate Forum"
    subtitle = "All candidates running in the 2022 election for a seat on the school board have accepted an invitation to attend this event.  The forum will be held in the PHS Ambassador Chris Stevens Library on September 22nd from 4:30 PM to 6:30 PM.  Please pre-register (so we can ask for a larger venue if needed) and arrive early.  Registered attendees qualify for raffle prizes."
    buttonText = "Register for free"
    url = "https://docs.google.com/forms/d/1EqrCdvsi629MPe1MsZF8t2ZkHjdpArVtUDKaL4G8zQc/edit"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.

    [[params.tiles.showcase]]
      title = "Best Practices"
      subtitle = "Top management should be subject matter experts who help discover the best path forward after independent research and study of the issues before them.  Batteries included.  Rubber stamping or kicking cans down the road not required."
      image = "pic01.jpg"
      imagew = "pic01.webp"
      url = "https://docs.google.com/forms/d/12DxD1Cb9urpHC6LFK4ArmorvEPlu0CoePFoNIxZ5QUY/edit"

    [[params.tiles.showcase]]
      title = "Standardized Test Results"
      subtitle = "A key differentiator for Piedmont schools are strong CAASPP and CAST test scores.  How are those results tracking year over year and grade after grade?  How well are similar school districts performing?"
      image = "pic02.jpg"
      imagew = "pic02.webp"
      url = "/attachments/"

    [[params.tiles.showcase]]
      title = "University and College Matriculation"
      subtitle = "Piedmont High utilizes a service to track graduate performance at the top 25 universities and colleges that are often considered 'reach' schools by applicants. PUSD graduate attendance at these schools has been steadily declining over the past decade."
      image = "pic03.jpg"
      imagew = "pic03.webp"
      url = "https://harititan.com/article/matriculation-counts"

    [[params.tiles.showcase]]
      title = "Transparency"
      subtitle = "Open government legislation helps but is not enough.  It is still very hard to find out all the pros and cons of any decision already made or being considered.  Candidates for office should not have hidden agendas."
      image = "pic04.jpg"
      imagew = "pic04.webp"
      url = "https://harititan.com/Transparency_Lost.webp"

    [[params.tiles.showcase]]
      title = "Educational Pathways"
      subtitle = "Helping every student achieve their learning potential through options for greater teacher attention, greater choice in electives, and advanced or accelerated study."
      image = "pic05.jpg"
      imagew = "pic05.webp"
      url = "https://docs.google.com/document/d/1zPe_g-9iYJFaRL5rtlnZcCgeTeI6Yib5yvUX1YFccNU/edit"

    [[params.tiles.showcase]]
      title = "In-person Instruction"
      subtitle = "K-12 students need supervision prior to development of independent learning skills.  Pandemic responses should be managed by epidemiologists at the county and state levels, not at each individual school district."
      image = "pic06.jpg"
      imagew = "pic06.webp"
      url = "https://harititan.com/article/epidemiologists-should-lead-way"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "About Us"
    subtitle = """Parents for Educational Excellence in Piedmont, aka PEEP, is a 501(c)(4) nonprofit corporation
    organized for charitable, educational, and scientific purposes to examine and promote educational
    excellence within the Piedmont Unified School District.  To maximize educational opportunities that best 
    prepare high school graduates for success in future academic or vocational programs, subject to the contraints 
    of school district budgets and contractual agreements.  We are continually striving for 
    academic excellence on par with the finest schools in the Bay Area."""
    buttonText = "Join our Mission"
    url = "https://www.paypal.com/donate/?hosted_button_id=ZWQ6MRRWALRXQ"


  # Contact section
  [params.contact]
    enable = false
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.


  # Footer section
  [params.footer]
    enable = true
    copyright = "Parents for Educational Excellence in Piedmont (Est. 2020, FEIN: 85-3820446), Piedmont, California, 94611"
